# makefile.mk - generate makefile
# $Header: /cvs/wlv/src/cedamk/mk/makefile.mk,v 1.22 2008/05/09 19:20:16 build Exp $

all:: makefile

$(ceda_mk_dir)/mk/arch.mk: ;		# Speed up makefile processing
$(ceda_mk_dir)/mk/defs-$(ARCH).mk: ;	# Speed up makefile processing

include $(ceda_mk_dir)/mk/arch.mk
include $(ceda_mk_dir)/mk/defs-$(ARCH).mk

# These variables are overriden on the command line
LOCAL_ROOT=.
LOCATION=.
SOURCEROOT=$(DEFAULT_SOURCEROOT)
CEDAMK=$$(dir $$(HPEESOF_DIR))/cedamk


# to speed up things These variables may be overriden on the command line
#
ifeq  (win,$(findstring win,$(ARCH)))
#ROOT_PATH:="$(shell cygpath -a -u $(LOCAL_ROOT))"
ROOT_PATH:=$(LOCAL_ROOT)
else
ROOT_PATH:=$(shell cd $(LOCAL_ROOT); pwd)
endif

RULES = \# Do not edit this file.  Add your definitions to the make-defs\n\
\# file in the current directory.\n\n\
\# root of source tree\n\
LOCAL_ROOT=$(LOCAL_ROOT)\n\n\
\# absolute PATH of root on filesystem\n\
ROOT_PATH=$(ROOT_PATH)\n\n\
\# location relative to root\n\
LOCATION=$(LOCATION)\n\n

ifneq ($(SOURCEROOT),$(DEFAULT_SOURCEROOT))
RULES += \# source root\n\
SOURCEROOT=$(SOURCEROOT)\n\n
endif

ifndef  PROJECT_PUBLIC_INCPATH
ifndef PROJECT_NAME
PROJECT_NAME=$(shell echo "$(LOCATION)" | sed -e 's/.*projects\///; s/\/.*//')
endif
ifndef PUBILIC_INCLUDE_PROJ_NAME
PUBILIC_INCLUDE_PROJ_NAME=$(PROJECT_NAME)
endif
PROJECT_PUBLIC_INCPATH=$(LOCAL_ROOT)/projects/$(PROJECT_NAME)/include/$(PUBILIC_INCLUDE_PROJ_NAME)
endif

ifneq ($(findstring $(SOURCEROOT),$(LOCATION)),)

OBJPATH_32BIT = $(subst $(LOCAL_ROOT)/$(SOURCEROOT),$$(LOCAL_ROOT)/obj.$$(ARCH_32BIT),$(LOCAL_ROOT)/$(LOCATION))
OBJPATH_64BIT = $(subst $(LOCAL_ROOT)/$(SOURCEROOT),$$(LOCAL_ROOT)/obj.$$(ARCH_64BIT),$(LOCAL_ROOT)/$(LOCATION))
OBJPATH = $(subst $(LOCAL_ROOT)/$(SOURCEROOT),$$(LOCAL_ROOT)/obj.$$(ARCH),$(LOCAL_ROOT)/$(LOCATION))

RULES += \# location relative to object files\n\
SRCPATH=$(LOCAL_ROOT)/$(LOCATION)\n\n\
PROJECT_PUBLIC_INCPATH=$(PROJECT_PUBLIC_INCPATH)\n\n\
\# location of object files\n\
OBJPATH_32BIT=$(OBJPATH_32BIT)\n\
OBJPATH_64BIT=$(OBJPATH_64BIT)\n\
OBJPATH=$(OBJPATH)\n\n

endif

RULES += \# location of master make files\n\
CEDAMK = $(subst $$,$$$$,$(CEDAMK))\n\
ifndef ceda_mk_dir\n\
export ceda_mk_dir = $(CEDAMK)\n\
endif\n\n


ifdef PROJECTMK
RULES += \# location of project make files\n\
PROJECTMK = $(subst $$,$$$$,$(PROJECTMK))\n\
ifndef project_mk_dir\n\
export project_mk_dir = $(PROJECTMK)\n\
endif\n\n
endif

RULES += include $$(ceda_mk_dir)/mk/dir.mk

makefile: $(ceda_mk_dir)/mk/makefile.mk
	@$(ECHO) Updating $(LOCATION)/makefile
	@rm -f $@
	$(at)$(ECHO) ' $(RULES)' >$@
