/*
   This file is generated by the make system to enable win32 shared
   libraries.  It must be the last included file.
*/

#undef linkerImport
#undef DllImport

#if defined(WIN32)
    #if defined(linker_DLL_BUILD)
        #define DllImport  __declspec(dllexport)
    #else 
        #define DllImport  __declspec(dllimport)
    #endif
#else
    #define DllImport
#endif
