netsh advfirewall firewall add    rule name=hpeesofemx             dir=in action=allow program="C:\Keysight\ADS2020\bin\hpeesofemx.exe"         enable=yes profile=domain
netsh advfirewall firewall add    rule name=oaFSLockD              dir=in action=allow program="C:\Keysight\ADS2020\bin\oaFSLockD.exe"          enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofg2p               dir=in action=allow program="C:\Keysight\ADS2020\bin\eesofg2p.exe"           enable=yes profile=domainn
netsh advfirewall firewall add    rule name=MomEngine_64           dir=in action=allow program="C:\Keysight\ADS2020\Momentum\2020.00\win32_64\bin\MomEngine.exe" enable=yes profile=domain                                enable=yes profile=domain
netsh advfirewall firewall add    rule name=FemEngine_64           dir=in action=allow program="C:\Keysight\ADS2020\Momentum\2020.00\win32_64\bin\FemEngine.exe"     enable=yes profile=domain
netsh advfirewall firewall add    rule name=momengine_64           dir=in action=allow program="C:\Keysight\ADS2020\Momentum\2020.00\win32_64\bin\momengine.exe" enable=yes profile=domain                                enable=yes profile=domain
netsh advfirewall firewall add    rule name=femengine_64           dir=in action=allow program="C:\Keysight\ADS2020\Momentum\2020.00\win32_64\bin\femengine.exe"     enable=yes profile=domain
netsh advfirewall firewall add    rule name=ads_python_64          dir=in action=allow program="C:\Keysight\ADS2020\tools\win32_64\python\bin\python.exe"                       enable=yes profile=domain
netsh advfirewall firewall add    rule name=ads_pythonw_64         dir=in action=allow program="C:\Keysight\ADS2020\tools\win32_64\python\bin\pythonw.exe"                      enable=yes profile=domain
netsh advfirewall firewall add    rule name=ads_fem_python_64      dir=in action=allow program="C:\Keysight\ADS2020\fem\2020.00\bin\Win64\tools\win32\python\python.exe"  enable=yes profile=domain
netsh advfirewall firewall add    rule name=ads_fem_pythonw_64     dir=in action=allow program="C:\Keysight\ADS2020\fem\2020.00\bin\Win64\tools\win32\python\pythonw.exe" enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofcksimsetup_64     dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofcksimsetup.exe"                      enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofClmClient_64      dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofClmClient.exe"                       enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpsh_64            dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpsh.exe"                             enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpshd_64           dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpshd.exe"                            enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpvm_64            dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpvm.exe"                             enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpvm_halter_64     dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpvm_halter.exe"                      enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpvm_imply_kill_64 dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpvm_imply_kill.exe"                  enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpvm_multitool_64  dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpvm_multitool.exe"                   enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpvmd3_64          dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpvmd3.exe"                           enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpvmgs_64          dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpvmgs.exe"                           enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpvmhoster_64      dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpvmhoster.exe"                       enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofpvmtracer_64      dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofpvmtracer.exe"                       enable=yes profile=domain
netsh advfirewall firewall add    rule name=eesofsc_64             dir=in action=allow program="C:\Keysight\ADS2020\pvm3\bin\win32_64\eesofsc.exe"                              enable=yes profile=domain
netsh advfirewall firewall add    rule name=ads_sshd_64            dir=in action=allow program="%SYSTEMDRIVE%\Program Files (x86)\ICW\Bin\sshd.exe"                            enable=yes profile=domain
netsh advfirewall firewall add    rule name=SystemVueEngine_64     dir=in action=allow program="C:\Keysight\ADS2020\SystemVue\2018.10\win32_64\bin\SystemVueEngine.exe" 	   enable=yes profile=domain                                enable=yes profile=domain