/* Copyright Keysight Technologies 2002 - 2011 */ 
LOCAL const char sccs_cui_circuit_template[]="@(#) $Source: /cvs/sr/src/geminiui/modelbuilder/MutInd.c,v $ $Revision: 1.6 $ $Date: 2011/08/27 00:17:20 $";

/******************************************************************************

   This template file can be modified by the user, it will never be modified
   by the Analog Model Development interface.  The structure of the files
   is (assuming user's model is called XYZ):

   XYZ_h.c         This file is auto-generated each time during the compile
                   process. It includes:

                   userdefs.h    the header file (copied to the local
                                 project's network directory only once).
                                 The file includes the <math.h> system
                                 header file.

                   XYZ.c         this file

   XYZ.dsn         This is the symbol file.

   XYZ.ael         This file contains the AEL code necessary to describe
                   the component and its parameters to the ADS design
                   environment (note that an .atf version of this file
                   is automatically generated by ADS when the component
                   is loaded).


   Each of the function calls below can be modified by the user.  Note
   that all functions are not necessarily used, this depends on the
   settings in the Code Options...  dialog box (the XYZ_h.c file
   redirects unused functions to NULL).

   Several other files will be installed in the networks directory:

   userindx.c      This file is for backwards compatibility with the
                   Series IV Senior interface. Once copied, it is never
                   modified by the Analog Model Development interface.

   cui_indx.c      This file is auto-generated each time a compile/link
                   is performed. It contains the list of calls from the
                   simulator to link in the boot_modules in the user's
                   code.
   hpeesof*.mak    This is the makefile that will be used to compile/link
                   (* = debug or opt).  It will #include two other files:

                   modelbuilder.mak   This file is auto-generated each
                                      time and contains the files to
                                      complile/link based on the dialog
                                      box settings.

                   user.mak           This file is copied only once and
                                      never modified by the Analog Model
                                      Development interface. It can be
                                      modified by the user.

*******************************************************************************/

#define STDTEMP 27.0

static COMPLEX negative(COMPLEX x); 
static COMPLEX complex_div(COMPLEX x, COMPLEX y);
static char ErrMsg[101];


/******************************************************************************/


/* Add Y-parameter function calls here for LINEAR models only (the
   linear portion of a nonlinear model is added in the analyze_lin
   procedure).                                                                */
static boolean compute_y (
  UserInstDef *userInst,
  double omega,
  COMPLEX *yPar)

{
    /**********************************************

          0        2 
          ----L1-----

          1        3
          ----L2-----

          ZL1 = R1 + j w * L1
          ZL2 = R2 + j w * L2
          Zm  = j w * M
          Zd = ( ZL1 * Zl2 - Zm * Zm)

                 [   ZL2     -Zm     -ZL2      Zm  ] [ ]   [ ]
          1/Zd * [  -Zm       ZL1     Zm      -ZL1 ] [V] = [I]
                 [  -ZL2      Zm      ZL2     -Zm  ] [ ]   [ ]
                 [   Zm      -ZL1    -Zm       ZL1 ] [ ]   [ ]

    **********************************************/

  double L1, L2, K, R1, R2, Rtiny, Lw1, Lw2, Lwm;
  UserParamData *pData = userInst->pData;
  COMPLEX zero, ZL1, ZL2, Zm, Zd;

  zero.real = 0.0;  zero.imag = 0.0;

  Rtiny = 1e-4;

  L1 = pData[0].value.dVal;
  L2 = pData[1].value.dVal;
  R1 = pData[2].value.dVal < Rtiny ? Rtiny : pData[2].value.dVal;
  R2 = pData[3].value.dVal < Rtiny ? Rtiny : pData[3].value.dVal;
  K =  pData[4].value.dVal;

  ZL1.real = R1; 
  ZL1.imag = Lw1 = omega * L1;
  ZL2.real = R2;
  ZL2.imag = Lw2 = omega * L2;

  if( L1 < 0 || L2 < 0)
  { 
    sprintf( ErrMsg, "Error: found invalid inductance in %s",
             userInst->tag);
    send_info_to_scn( ErrMsg );
    return FALSE;
  }

  Zm.real  = 0;
  Zm.imag  = Lwm = omega * K * sqrt( L1 * L2 );

  Zd.real = R1 * R2 - Lw1 * Lw2 + Lwm * Lwm;
  Zd.imag = R1 * Lw2 + R2 * Lw1;

  if(omega<=1.0)
  {
        yPar[0].real = yPar[10].real = 1/R1;
        yPar[0].imag = yPar[10].imag = 0.0;
        yPar[1] = yPar[11] = zero;
        yPar[2] = yPar[8]  = negative(yPar[0]);
        yPar[3] = yPar[9]  = zero;
        yPar[4] = yPar[14] = zero;
        yPar[5].real = yPar[15].real = 1/R2;
        yPar[5].imag = yPar[15].imag = 0.0;
        yPar[6] = yPar[12] = zero;
        yPar[7] = yPar[13] = negative(yPar[5]);
  } 
  else 
  {
        yPar[0] = yPar[10] = complex_div(ZL2,Zd); /*  ZL2/Zd */
        yPar[1] = yPar[11] = complex_div(negative(Zm),Zd);
        yPar[2] = yPar[8]  = negative(yPar[0]);   /* -ZL2/Zd */
        yPar[3] = yPar[9]  = negative(yPar[1]);   /* Zm / Zd */
        yPar[4] = yPar[14] = yPar[1];             /* -Zm/Zd  */
        yPar[5] = yPar[15] = complex_div(ZL1,Zd); /* ZL1/Zd  */
        yPar[6] = yPar[12] = yPar[3];             /* Zm / Zd */
        yPar[7] = yPar[13] = negative(yPar[5]);   /* -ZL1/Zd */
  }

  return TRUE;
}

/* Add pre-analysis routines here.                                            */
static boolean pre_analysis (
  UserInstDef *userInst)
{
  boolean status = TRUE;

  return status;
}


/* Add post-analysis routines here.                                           */
static boolean post_analysis (
  UserInstDef *userInst)
{
  boolean status = TRUE;

  return status;
}


/* Add modify_param routines here. This function is called when any device
   parameter values change
*/
static boolean modify_param (
  UserInstDef *userInst)
{
  boolean status = TRUE;

  return status;
}

/* Add LINEAR noise contribution here.                                        */
static boolean compute_n (
  UserInstDef *userInst,
  double omega,
  COMPLEX *yPar,
  COMPLEX *nCorr)
{
  UserElemDef *userDef = userInst->userDef;

  return passive_noise(yPar, STDTEMP, userDef->numExtNodes, nCorr);
}


/* Add Linear contribution for NONLINEAR models here (use compute_y to
   add linear model y-parameters).                                            */
static boolean analyze_lin (
  UserInstDef *userInst,
  double omega)
{
  boolean status = TRUE;

  return status;
}


/* Add Nonlinear contribution for NONLINEAR models here.                      */
static boolean analyze_nl (
  UserInstDef *userInst,
  double *vPin)
{
  boolean status = TRUE;

  return status;
}


/* Add small-signal AC model (linear + linearized) Y-parameters.              */
static boolean analyze_ac (
  UserInstDef *userInst,
  double *vPin,
  double omega)
{
  boolean status = TRUE;

  return status;
}


/* Add bias-dependent small-signal noise parameters here.                     */
static boolean analyze_ac_n (
  UserInstDef *userInst,
  double *vPin,
  double omega)
{
  boolean status = TRUE;

  return status;
}



/* Add transient response here.                                               */
static boolean analyze_tr(
  UserInstDef *userInst,
  double *vPin)
{
  boolean status = TRUE;
  UserParamData *pData = userInst->pData;
  double L1, L2, R1, R2, K;
  int ind1,ind2;

  L1 = pData[0].value.dVal;
  L2 = pData[1].value.dVal;
  R1 = pData[2].value.dVal;
  R2 = pData[3].value.dVal;
  K =  pData[4].value.dVal;

  /* add_tr_lossy_inductor and add_tr_inductor return a integer 
     which is inductor index. The index should be larger than 0 */
  ind1 = add_tr_lossy_inductor(userInst, 0, 2, R1, L1);
  ind2 = add_tr_lossy_inductor(userInst, 1, 3, R2, L2);

  if ( ind1 && ind2 )
  {
      status = add_tr_mutual_inductor(userInst, ind1, ind2, K);
  }
  else
     status = FALSE;

  return status;
}


/* Add setup ideal transmission line calls here                               */
static boolean fix_tr(
  UserInstDef *userInst)
{
  boolean status = TRUE;

  return status;
}


/* complex divide */
static COMPLEX complex_div(COMPLEX x, COMPLEX y)
{                    
        COMPLEX temp;
        double  denom;
        denom = (y.real * y.real) + (y.imag * y.imag);
        temp.real = ((x.real * y.real) + (x.imag * y.imag))/denom;
        temp.imag = ((x.imag * y.real) - (x.real * y.imag))/denom;
        return (temp);
}


/* complex negative */
static COMPLEX negative(COMPLEX x) 
{
        COMPLEX temp;
        temp.real = -x.real;
        temp.imag = -x.imag;
        return(temp);
}

